### ISSUE TITLE
Allow closing panel in single select mode

### ISSUE THREAD

**Issue by mspae** [mynamesleon/aria-tablist#20]
Is this something you would consider accepting a MR for?

**Comment by mynamesleon** [comment]
Hi @mspae.

Within a single-select tablist, the convention (and expectation) is that the tabs operate sort of like a radiolist, where one always remains active.

I could certainly add an option so that a click on an already active tab closes it. If you need the functionality immediately, the library does already allow you to do this programmatically using the API's `.close(index)` method.

**Comment by mspae** [comment]
Thanks for the quick answer. I guessed that this was some kind of convention but didn't realise this could be implemented with aria-tablist with existing APIs.

I will implement it like this for now. I had this implemented in my local fork of the lib (https://github.com/mynamesleon/aria-tablist/commit/7161b05f840327eff3536796a572a9f7e5b67d9f – the commit is mangled with the other feature so would need to be unmangled anyway). If you want that MR (but then again you probably know of some aspects of this my naive implementation does not consider)
