### ISSUE TITLE
Please give instructions on howto with React/Gatsby pages

### ISSUE THREAD

**Issue by NetLancer** [mynamesleon/aria-tablist#6]
Its probably about my rather scarce knowledge of React ecosystem and components, but i found this library super useful (to me at least) and it would be real nice to have instruction about setting it up with React/Vue. 
Great thanx :)

**Comment by mynamesleon** [comment]
Hi, I'm glad you've found it useful :)

This is ultimately just a plain JS library like any other, so you'd integrate it with React/Vue in much the same way as you would normally. 

In terms of React, the basic approach would be to create a ref for your container element, and then use the lifecycle methods (or cleverly handled `useEffect` hooks) to initiate the library, and then also destroy and re-initialise it when needed (such as when/if new child items will be added).

A very basic (and inefficient) example might be:

```js
const TabList = ({ children, ...options }) => {
    const tablist = useRef(null);
    const tablistApi = useRef(null);

    useEffect(() => {
        // make sure tablist ref contains the element, and initialise
        if (tablist.current) {
            tablistApi.current = AriaTablist(tablist.current, options);
        }

        // destroy the tablist when the effect updates 
        // (including when the component unmounts, for memory cleanup)
        return () => {
            if (tablistApi.current) {
                tablistApi.current.destroy();
            }
        }
    });

    return (
        <div ref={tablist}>
            {children}
        </div>
    )
};
```

This example is inefficient because it would be destroying and re-initialising the tablist functionality with every update. You'd want to include some specific logic to make sure that only happens when necessary (e.g. querying the elements inside to make sure they've actually changed. 

I hope this is enough of a general idea to get you going though? (I haven't used Vue since version 1 I'm afraid, so I'm a bit out of touch with their component ecosystem at the moment. Hopefully this React example is enough?)

**Comment by NetLancer** [comment]
Seems good, but i just had to use something a little simpler for my webpage. 
Down the road i"am gonna try this out definitely and see if it works smooth in my gatsby site. 
Thank you for nice widget!
